name: static

on:
    push:
    pull_request:

jobs:
    static:
        name: phpstan + pint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
                  extensions: sqlite3, pdo_sqlite

            - name: Install dependencies
              run: composer update --no-interaction --prefer-dist

            - name: PHPStan
              run: vendor/bin/phpstan analyse --memory-limit=1G --no-progress

            - name: Pint (dry run)
              run: vendor/bin/pint --test
